// Variables need to be put on the creatures claw/slam and the Creature.  Choose the OnHitCast Touch attack on the item.

#include "x2_inc_spellhook"
#include "x2_inc_switches"
#include "acr_creature_i"
#include "NW_I0_SPELLS"


void main()
{
	object oTarget = GetSpellTargetObject();
	//int SaveDC = GetHitDice(OBJECT_SELF) / 2 + GetAbilityModifier(ABILITY_CHARISMA, OBJECT_SELF) + 10;

if(GetLocalString(OBJECT_SELF, "ACR_TOUCH_ATTACK") == "WRAITH")
	{
		if(GetObjectType(oTarget) == OBJECT_TYPE_CREATURE)
		{
			int nTouch = TouchAttackMelee(oTarget);
			int nDrain = d6(1);
			if(nTouch && !FortitudeSave(oTarget, 14, SAVING_THROW_TYPE_NEGATIVE, OBJECT_SELF))
			{
				if(nDrain >  GetAbilityScore(oTarget, ABILITY_CONSTITUTION) &&
				   !GetIsImmune(oTarget, IMMUNITY_TYPE_ABILITY_DECREASE))
				{
					ApplyEffectToObject(DURATION_TYPE_INSTANT, EffectDeath(), oTarget);
				}
				ApplyEffectToObject(DURATION_TYPE_PERMANENT, SupernaturalEffect(EffectTemporaryHitpoints(5)), OBJECT_SELF);
				ApplyEffectToObject(DURATION_TYPE_PERMANENT, SupernaturalEffect(EffectAbilityDecrease(ABILITY_CONSTITUTION, nDrain)), oTarget);
				SendMessageToPC(oTarget, GetName(OBJECT_SELF) + " touches you! You feel more frail.");
				//ApplyEffectToObject(DURATION_TYPE_INSTANT, EffectDamage(nDamage), oTarget);
				ApplyEffectToObject( DURATION_TYPE_INSTANT, EffectVisualEffect( VFX_IMP_PULSE_NEGATIVE ), oTarget );
			}
		}
	}
	else if(GetLocalString(OBJECT_SELF, "ACR_TOUCH_ATTACK") == "GHOST")
	{
		if(GetObjectType(oTarget) == OBJECT_TYPE_CREATURE)
	{
			int nTouch = TouchAttackMelee(oTarget);
			int nDamage = d6(1);
			SendMessageToPC(oTarget, "nDamage = " + IntToString(nDamage));
			int nDrain = d4(1);
			if(nTouch)
			{
				int nAbility = Random(6);
				
				if(GetLevelByClass(CLASS_TYPE_FIGHTER, oTarget) ||
				   GetLevelByClass(CLASS_TYPE_RANGER, oTarget))
				{  
				    if(Random(3) == 1) {nAbility = ABILITY_STRENGTH;}
				}
				
				if(GetLevelByClass(CLASS_TYPE_ROGUE, oTarget))
				{
					if(Random(3) == 1) {nAbility = ABILITY_DEXTERITY;}
				}
				
				if(GetLevelByClass(CLASS_TYPE_SORCERER, oTarget) ||
				   GetLevelByClass(CLASS_TYPE_FAVORED_SOUL, oTarget) ||
				   GetLevelByClass(CLASS_TYPE_BARD, oTarget))
				{  
				    if(Random(3) == 1) {nAbility = ABILITY_CHARISMA;}
				}
				if(GetLevelByClass(CLASS_TYPE_CLERIC, oTarget) ||
				   GetLevelByClass(CLASS_TYPE_DRUID, oTarget) ||
				   GetLevelByClass(CLASS_TYPE_SPIRIT_SHAMAN, oTarget))
				{
					if(Random(3) == 1) {nAbility = ABILITY_WISDOM;}
				}
				if(GetLevelByClass(CLASS_TYPE_WIZARD, oTarget))
				{
					if(Random(3) == 1) {nAbility = ABILITY_INTELLIGENCE;}
				}
				
				SendMessageToAllDMs(GetName(oTarget) + " loses " + IntToString(nDamage) + " points of ability " + IntToString(nAbility));
	   
				string sMessage = GetName(OBJECT_SELF) + " touches you!";
				string sMessageAbility;
				if(nAbility == 0) {sMessageAbility = "Your muscles go slack.";}
				else if(nAbility == 1) {sMessageAbility = "Your limbs freeze up.";}
				else if(nAbility == 2) {sMessageAbility = "Your feel faint.";}
				else if(nAbility == 3) {sMessageAbility = "Your mind dulls.";}
				else if(nAbility == 4) {sMessageAbility = "Your panic clouds your judgement.";}
				else if((nAbility == 5) && GetLevelByClass(CLASS_TYPE_BARD, oTarget)) {sMessageAbility = "Your voice stutters.";}
				else if(nAbility == 5) {sMessageAbility = "Your confidence fails.";}
				
				SendMessageToPC(oTarget, sMessage);
				SendMessageToPC(oTarget, sMessageAbility);
				SendMessageToAllDMs(GetName(oTarget) + " touched by " + GetTag(OBJECT_SELF) + " got " + sMessageAbility);
				
				if(nDrain >  GetAbilityScore(oTarget, nAbility) &&
				   !GetIsImmune(oTarget, IMMUNITY_TYPE_ABILITY_DECREASE))
				{
					ApplyEffectToObject(DURATION_TYPE_INSTANT, EffectParalyze(), oTarget);
				}
				
        		ApplyEffectToObject(DURATION_TYPE_INSTANT, EffectHeal(5), OBJECT_SELF);
				ApplyEffectToObject(DURATION_TYPE_PERMANENT, SupernaturalEffect(EffectAbilityDecrease(nAbility, nDrain)), oTarget);
				ApplyEffectToObject(DURATION_TYPE_INSTANT, EffectDamage(nDamage), oTarget);
				ApplyEffectToObject(DURATION_TYPE_INSTANT, EffectVisualEffect( VFX_IMP_PULSE_NEGATIVE ), oTarget );
			}
		}
	}
	
	
	  
else if(GetLocalString(OBJECT_SELF, "ACR_TOUCH_ATTACK") == "ALLIP")
	{
		if(GetObjectType(oTarget) == OBJECT_TYPE_CREATURE)
		{
			int nTouch = TouchAttackMelee(oTarget);
        	int nDrain = d4(1);
			if(nTouch)
			{
				if(nDrain >  GetAbilityScore(oTarget, ABILITY_WISDOM) &&
				   !GetIsImmune(oTarget, IMMUNITY_TYPE_ABILITY_DECREASE))
				{
					ApplyEffectToObject(DURATION_TYPE_PERMANENT, EffectSleep(), oTarget);
				}			
				ApplyEffectToObject(DURATION_TYPE_PERMANENT, SupernaturalEffect(EffectTemporaryHitpoints(5)), OBJECT_SELF);
				ApplyEffectToObject(DURATION_TYPE_PERMANENT, SupernaturalEffect(EffectAbilityDecrease(ABILITY_WISDOM, nDrain)), oTarget);
				SendMessageToPC(oTarget, GetName(OBJECT_SELF) + " touches you! Panic clouds your judgement.");
				ApplyEffectToObject( DURATION_TYPE_INSTANT, EffectVisualEffect( VFX_IMP_PULSE_NEGATIVE ), oTarget );
			}
		}
	}
	 
	else if(GetLocalString(OBJECT_SELF, "ACR_TOUCH_ATTACK") == "WISP")
	{
		if(GetObjectType(oTarget) == OBJECT_TYPE_CREATURE)
		{
			int nTouch = TouchAttackMelee(oTarget);
			int nDamage = d8(2);
			//if(nTouch == 2) nDamage += d8(2);
			if(nTouch)
			{
				ApplyEffectToObject( DURATION_TYPE_INSTANT, EffectDamage( nDamage, DAMAGE_TYPE_ELECTRICAL ), oTarget );
			    SendMessageToPC(oTarget, GetName(OBJECT_SELF) + " touches you! You feel a jolt run through your body");
				ApplyEffectToObject( DURATION_TYPE_TEMPORARY, EffectBeam( VFX_BEAM_SHOCKING_GRASP, OBJECT_SELF, BODY_NODE_CHEST, FALSE ), oTarget, 1.0f );
			}
		}
   }
    
	else if(GetLocalString(OBJECT_SELF, "ACR_TOUCH_ATTACK") == "SHADOW")
	{
		if(GetObjectType(oTarget) == OBJECT_TYPE_CREATURE)
		{
			int nTouch = TouchAttackMelee(oTarget);
			int nDrain = d6(1);
			
		//	{
        
        //if(nTouch == 2) nDamage += d6();
		SendMessageToPC(oTarget, "nDrain = " + IntToString(nDrain));
		if(nTouch)
			{
				if(nDrain >  GetAbilityScore(oTarget, ABILITY_STRENGTH) &&
				   !GetIsImmune(oTarget, IMMUNITY_TYPE_ABILITY_DECREASE))
				{
					ApplyEffectToObject(DURATION_TYPE_INSTANT, EffectDeath(), oTarget);
				}
				ApplyEffectToObject(DURATION_TYPE_PERMANENT, ExtraordinaryEffect(EffectAbilityDecrease(ABILITY_STRENGTH, nDrain)), oTarget);
				SendMessageToPC(oTarget, GetName(OBJECT_SELF) + " touches you! Strength goes out of your limbs.");
				ApplyEffectToObject( DURATION_TYPE_INSTANT, EffectVisualEffect( VFX_IMP_PULSE_NEGATIVE ), oTarget );
			}
		//}
	 }
   }
 
  
	//{
    	else if(GetLocalString(OBJECT_SELF, "ACR_TOUCH_ATTACK") == "GREATER SHADOW")
		{
		if(GetObjectType(oTarget) == OBJECT_TYPE_CREATURE)
		{
			int nTouch = TouchAttackMelee(oTarget);
			int nDrain =  d8(1);			
		if(nTouch)
			{
				if(nDrain >  GetAbilityScore(oTarget, ABILITY_STRENGTH) &&
				   !GetIsImmune(oTarget, IMMUNITY_TYPE_ABILITY_DECREASE))
				{
					ApplyEffectToObject(DURATION_TYPE_INSTANT, EffectDeath(), oTarget);	
				}
				ApplyEffectToObject(DURATION_TYPE_PERMANENT, ExtraordinaryEffect(EffectAbilityDecrease(ABILITY_STRENGTH, nDrain)), oTarget);
				SendMessageToPC(oTarget, GetName(OBJECT_SELF) + " touches you! Your muscles go slack, your strength failing.");
				ApplyEffectToObject( DURATION_TYPE_INSTANT, EffectVisualEffect( VFX_IMP_PULSE_NEGATIVE ), oTarget );
			}
	//	}
	 }
  }
//}
}